//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by LaserScan.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDD_Bar_CNC                     103
#define IDR_MAINFRAME                   128
#define IDR_LaserScanTYPE               129
#define IDD_HardwareSettings            130
#define IDD_Initialization              131
#define IDD_Optics                      132
#define IDD_DIALOG1                     133
#define IDD_LaserControl                133
#define IDD_WorkingMode                 134
#define IDD_HardwareSettings_ScanHead   135
#define IDI_HELP                        140
#define IDI_Para                        141
#define IDI_LaserControl                142
#define IDI_ICON1                       143
#define IDI_CNC2000                     143
#define IDR_MENU1                       144
#define IDD_DIALOG2                     145
#define IDD_Wobbel                      200
#define IDD_Processing                  201
#define IDD_Automatic                   202
#define IDD_ParameterSettings           203
#define IDD_LaserControl_Settings       204
#define IDD_LaserControl_Status         205
#define IDD_Draw_TaskList               206
#define IDD_Draw                        207
#define IDD_Bar_ParameterSettings       208
#define IDD_Bar_LaserControl_Settings1  209
#define IDD_Bar_LaserControl_Settings   209
#define IDC_TREE_Hardware               1000
#define IDC_XPLUS                       1000
#define IDC_STATIC_Hardware             1001
#define IDC_XMINUS                      1001
#define IDC_YPLUS                       1002
#define IDC_EDIT2                       1003
#define IDC_RADIO1                      1003
#define IDC_EDITX                       1003
#define IDC_EDIT1                       1004
#define IDC_EDIT_SerialPortParameters   1004
#define IDC_Line_Mark                   1004
#define IDC_YMINUS                      1004
#define IDC_EDIT3                       1005
#define IDC_RADIO3                      1005
#define IDC_EDIT_SerialPortParameters2  1005
#define IDC_EDIT_SerialPort_Response    1005
#define IDC_Plot                        1005
#define IDC_EDITY                       1005
#define IDC_EDIT4                       1006
#define IDC_RADIO4                      1006
#define IDC_STATIC2                     1006
#define IDC_STATIC_Py_Error             1006
#define IDC_Line                        1006
#define IDC_ZPLUS                       1006
#define IDC_EDIT5                       1007
#define IDC_BUTTON1                     1007
#define IDC_RADIO5                      1007
#define IDC_STATIC3                     1007
#define IDC_STATIC_Ts_Error             1007
#define IDC_Arc                         1007
#define IDC_ZMINUS                      1007
#define IDC_EDIT6                       1008
#define IDC_RADIO6                      1008
#define IDC_STATIC4                     1008
#define IDC_STATIC_Ps_Error             1008
#define IDC_BUTTON2                     1008
#define IDC_Rectangle                   1008
#define IDC_EDITZ                       1008
#define IDC_EDIT7                       1009
#define IDC_RADIO7                      1009
#define IDC_STATIC9                     1009
#define IDC_STATIC_Px_Error             1009
#define IDC_EDITX2                      1009
#define IDC_STATIC_Plot                 1010
#define IDC_EDITY2                      1010
#define IDC_RADIO2                      1011
#define IDC_STATIC_Line                 1011
#define IDC_EDITZ2                      1011
#define IDC_Description                 1012
#define IDC_STATIC_Arc                  1012
#define IDC_RADIO8                      1013
#define IDC_RADIO10                     1013
#define IDC_STATIC_Description          1013
#define IDC_STATIC_Rectangle            1013
#define IDC_STATIC_Initialization       1014
#define IDC_Circle_Filled               1014
#define IDC_BUTTON3                     1014
#define IDC_RADIO9                      1015
#define IDC_STATIC_Px                   1015
#define IDC_Plot_Y                      1015
#define IDC_STATIC1                     1016
#define IDC_STATIC_Py                   1016
#define IDC_Plot_Duration               1016
#define IDC_STATIC_Ts                   1017
#define IDC_Line_StartX                 1017
#define IDC_EDITX_POSITION              1017
#define IDC_STATIC_Ps                   1018
#define IDC_Plot_X                      1018
#define IDC_EDITY_POSITION              1018
#define IDC_STATIC_LM                   1019
#define IDC_Line_StartY                 1019
#define IDC_EDITZ_POSITION              1019
#define IDC_Line_EndX                   1020
#define IDC_EDIT_STEPL                  1020
#define IDC_Line_EndY                   1021
#define IDC_Line_Duration               1022
#define IDC_Rectangule_Unfilled         1023
#define IDC_Arc_StartX                  1024
#define IDC_STATIC1_LaserDelay          1025
#define IDC_Arc_StartY                  1025
#define IDC_STATIC2_LaserOnDelay        1026
#define IDC_Arc_CenterX                 1026
#define IDC_STATIC3_LaserOffDelay       1027
#define IDC_Arc_Angle                   1027
#define IDC_EDIT1_LaserOnDelay          1028
#define IDC_Arc_CenterY                 1028
#define IDC_EDIT2_LaserOffDelay         1029
#define IDC_Rec_StartX                  1029
#define IDC_STATIC4_JumpDelay           1030
#define IDC_Rec_StartY                  1030
#define IDC_EDIT3_JumpDelay             1031
#define IDC_Rec_EndX                    1031
#define IDC_STATIC5_MarkDelay           1032
#define IDC_CHECK_XHOME                 1032
#define IDC_EDIT4_MarkDelay             1033
#define IDC_Rectangule_X_Filled         1033
#define IDC_CHECK_YHOME                 1033
#define IDC_STATIC6_PolygonDelay        1034
#define IDC_Rec_EndY                    1034
#define IDC_CHECK_ZHOME                 1034
#define IDC_EDIT5_PolygonDelay          1035
#define IDC_Rectangule_Y_Filled         1035
#define IDC_CHECK_STEP                  1035
#define IDC_STATIC9_JumpSpeed           1036
#define IDC_Line_Jump                   1036
#define IDC_EDIT6_JumpSpeed             1037
#define IDC_Draw_Tree                   1037
#define IDC_STATIC10_MarkSpeed          1038
#define IDC_EDIT7_MarkSpeed             1039
#define IDC_Initialize                  1039
#define IDC_STATIC7_ScannerDelay        1040
#define IDC_Implement                   1040
#define IDC_STATIC8_Speed               1041
#define IDC_Add                         1041
#define IDC_STATIC11_EdgeThreshold      1042
#define IDC_Remove                      1042
#define IDC_EDIT8_EdgeThreshold         1043
#define IDC_Circle_Unfilled             1043
#define IDC_STATIC12_MinJumpDelay       1044
#define IDC_EDIT9_MinJumpDelay          1045
#define IDC_STATIC13_JumpLengthLimit    1046
#define IDC_EDIT10_JumpLengthLimit      1047
#define IDC_CHECK1_variablePolygonDelay 1048
#define IDC_CHECK2_UsePolygonTable      1049
#define IDC_TREE_WorkingMode            1050
#define IDC_CHECK3_MoveZAxis            1050
#define IDC_STATIC_WorkingMode          1051
#define IDC_STATIC2_LaserOnDelay_unit   1051
#define IDC_STATIC4_JumpDelay_unit      1052
#define IDC_STATIC3_LaserOffDelay_unit  1053
#define IDC_STATIC5_MarkDelay_unit      1054
#define IDC_STATIC2_LaserOnDelay6       1055
#define IDC_STATIC6_PolygonDelay_unit   1055
#define IDC_STATIC9_JumpSpeed_unit      1056
#define IDC_STATIC10_MarkSpeed_unit     1057
#define IDC_STATIC6_PolygonDelay_unit2  1058
#define IDC_STATIC6_PolygonDelay_unit3  1059
#define IDC_STATIC6_PolygonDelay_unit4  1060
#define IDC_TREE_LaserControl           1061
#define IDC_STATIC_LaserControl         1062
#define IDC_STATIC_LaserInputSignalMode 1063
#define IDC_STATIC_LaserInputSignal     1064
#define IDC_STATIC_StanbySignal         1065
#define IDC_STATIC_ADOutput             1066
#define IDC_STATIC_Laser                1067
#define IDC_EDIT_LaserPower             1068
#define IDC_STATIC_LaserPower           1069
#define IDC_EDIT_LaserSetpoint          1070
#define IDC_BUTTON_ResetError           1070
#define IDC_STATIC_LaserSetpoint        1071
#define IDC_STATIC_LaserStatus          1071
#define IDC_STATIC_LaserSetpoint_Unit   1071
#define IDC_EDIT_LaserFrequency         1072
#define IDC_STATIC_LaserTemperature     1072
#define IDC_STATIC_LaserFrequency       1073
#define IDC_STATIC_BackReflection       1073
#define IDC_STATIC_ModelNumber          1074
#define IDC_STATIC_LaserSetpoint2       1074
#define IDC_STATIC_AutoLaserControl     1075
#define IDC_STATIC_StatusShowing        1075
#define IDC_STATIC_LaserFrequencyRead   1076
#define IDC_STATIC_LaserFrequency_Unit  1076
#define IDC_STATIC_CaseTemperature      1077
#define IDC_STATIC_LaserFrequency_Unit2 1077
#define IDC_STATIC_HeadTemperature      1078
#define IDC_RADIO_LaserCO2mode          1078
#define IDC_STATIC_LowerDeck            1079
#define IDC_STATIC_HalfPeriod           1079
#define IDC_STATIC_LowerDeckTemp        1079
#define IDC_STATIC_FirmwareVersion      1080
#define IDC_RADIO_LaserYAG2mode         1080
#define IDC_RADIO_LaserYAG3mode         1081
#define IDC_RADIO_LaserModeYAG2         1082
#define IDC_STATIC_PulseLength          1083
#define IDC_RADIO_Lasermode4            1084
#define IDC_RADIO_LaserYAG5mode         1085
#define IDC_RADIO_LaserYAG3mode2        1086
#define IDC_EDIT_HalfPeriod             1087
#define IDC_EDIT_PulseLength            1088
#define IDC_EDIT_PulseLength2           1089
#define IDC_EDIT_FrequencySignal        1089
#define IDC_STATIC_Frequency            1090
#define IDC_STATIC_FirstPulseKillerLength 1091
#define IDC_EDIT_FirstPulseKillerLength 1092
#define IDC_STATIC_Standby_HalfPeriod   1093
#define IDC_EDIT_HalfPeriod2            1094
#define IDC_EDIT_StanbyHalfPeriod       1094
#define IDC_EDIT_PulseLength3           1095
#define IDC_EDIT_StandbyFrequency       1095
#define IDC_STATIC_Frequency2           1096
#define IDC_CHECK1                      1097
#define IDC_CHECK2                      1098
#define IDC_CHECK3                      1099
#define IDC_CHECK4                      1100
#define IDC_CHECK5                      1101
#define IDC_STATIC_FLPALO               1102
#define IDC_STATIC_180DPSOL             1103
#define IDC_STATIC_DLS                  1104
#define IDC_STATIC_SLSLA                1105
#define IDC_STATIC_Qswitchdelay         1106
#define IDC_EDIT_PulseLength4           1107
#define IDC_EDIT_QSwitchDelay           1107
#define IDC_EDIT_StandbyFrequency2      1108
#define IDC_EDIT_StandbyPulseLength     1108
#define IDC_LaserControl_Accept         1109
#define IDC_STATIC_StandbyPulseLength   1110
#define IDC_STATIC_SerialPortSettings   1111
#define IDC_STATIC_SerialPortNumber     1112
#define IDC_STATIC_SerialPort_Parameters 1113
#define IDC_EDIT_SerialpPort            1114
#define IDC_STATIC_SerialPort_StringManualSend 1115
#define IDC_EDIT_SerialpPort_StringManualSend 1116
#define IDC_STATIC_Serialport_Response  1117
#define IDC_ManualSend                  1118
#define IDC_MSCOMM1                     1119
#define IDC_SerialPort_MSCOMM           1119
#define IDC_SerialPort_MSCOMM_Status    1119
#define IDC_Draw_MSCOMM                 1119
#define IDC_STATIC_HalfPeriod_Unit      1120
#define IDC_LaserControl_StatusGeneral  1121
#define IDC_STATIC_HalfPeriod_Unit2     1121
#define IDC_Status_InternalFrequency    1122
#define IDC_STATIC_HalfPeriod_Unit3     1122
#define IDC_Status_MinFrequency         1123
#define IDC_STATIC_HalfPeriod_Unit4     1123
#define IDC_Status_MaxFrequency         1124
#define IDC_STATIC_HalfPeriod_Unit5     1124
#define IDC_Status_CaseTemp             1125
#define IDC_STATIC_HalfPeriod_Unit6     1125
#define IDC_Status_HeadTemp             1126
#define IDC_STATIC_LaserFrequency_Unit3 1126
#define IDC_Status_LowDeckTemp          1127
#define IDC_STATIC_BackReflectinShow    1128
#define IDC_STATIC_ModelNumShow         1129
#define IDC_Status_Error                1130
#define IDC_STATIC_Error                1131
#define IDC_STATIC_StatusGeneral        1132
#define IDC_STATIC_FirewareVerionShow   1133
#define IDC_STATIC_LaserPower_Unit      1133
#define IDC_Status_BackReflection       1134
#define IDC_LaserOn                     1134
#define IDC_Status_ModelNumber          1135
#define IDC_LaserOn2                    1135
#define IDC_LaserOff                    1135
#define IDC_Modulation                  1135
#define IDC_Status_FirmwareVersion      1136
#define IDC_BUTTON4                     1136
#define IDC_Exit                        1136
#define IDC_SLIDER1                     1137
#define IDC_LaserControl_Exit           1139
#define IDC_Accept                      1140
#define IDC_SCROLLBAR1                  1141
#define ID_HARDWARE_HARDWARESETTINGS    32771
#define ID_HARDWARE_LASERCONTROL        32772
#define ID_HARDWARE_WORKINGMODE         32773
#define ID_HARDWARE_PARAMETERSETTINGS   32774
#define ID_OPERATION_DRAW               32775
#define ID_DRAWTOOLS                    32782
#define ID_DRAWTOOLS_32783              32783
#define ID_DRAWTOOLS_DOT                32784
#define ID_DRAWTOOLS_RECTANGLE          32785
#define ID_DRAWTOOLS_ELLIPSE            32786
#define ID_DRAWTOOLS_POLYGON            32787
#define ID_DRAW_32788                   32788
#define ID_DRAW_LINE                    32789
#define ID_DRAW_RECTANGLE               32790
#define ID_DRAW_ELLIPSE                 32791
#define ID_DRAW_POLYGON                 32792
#define ID__PROPERTIES                  32793
#define ID__COPY                        32794
#define ID__CUT                         32795
#define ID_LASER_IMPLEMENT              32796

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        146
#define _APS_NEXT_COMMAND_VALUE         32797
#define _APS_NEXT_CONTROL_VALUE         1142
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
