unit RTC5Import;
{
  Delphi Import Declarations for the SCANLAB RTC5-DLL
  This file was automatically generated at 21.12.2010
}
interface

const RTC5DLL = 'RTC5DLL.DLL';

type
  PWord     = ^Word;
  PLongInt  = ^LongInt;
  PLongWord = ^LongWord;

function  init_rtc5_dll(): LongWord; stdcall; external RTC5DLL;
procedure free_rtc5_dll(); stdcall; external RTC5DLL;
procedure set_rtc4_mode(); stdcall; external RTC5DLL;
procedure set_rtc5_mode(); stdcall; external RTC5DLL;
function  get_rtc_mode(): LongWord; stdcall; external RTC5DLL;
function  n_get_error(CardNo: LongWord): LongWord; stdcall; external RTC5DLL;
function  n_get_last_error(CardNo: LongWord): LongWord; stdcall; external RTC5DLL;
procedure n_reset_error(CardNo: LongWord; Code: LongWord); stdcall; external RTC5DLL;
function  n_set_verify(CardNo: LongWord; Verify: LongWord): LongWord; stdcall; external RTC5DLL;
function  get_error(): LongWord; stdcall; external RTC5DLL;
function  get_last_error(): LongWord; stdcall; external RTC5DLL;
procedure reset_error(Code: LongWord); stdcall; external RTC5DLL;
function  set_verify(Verify: LongWord): LongWord; stdcall; external RTC5DLL;
function  verify_checksum(Name: PChar): LongWord; stdcall; external RTC5DLL;
function  rtc5_count_cards(): LongWord; stdcall; external RTC5DLL;
function  acquire_rtc(CardNo: LongWord): LongWord; stdcall; external RTC5DLL;
function  release_rtc(CardNo: LongWord): LongWord; stdcall; external RTC5DLL;
function  select_rtc(CardNo: LongWord): LongWord; stdcall; external RTC5DLL;
function  get_dll_version(): LongWord; stdcall; external RTC5DLL;
function  n_get_serial_number(CardNo: LongWord): LongWord; stdcall; external RTC5DLL;
function  n_get_hex_version(CardNo: LongWord): LongWord; stdcall; external RTC5DLL;
function  n_get_rtc_version(CardNo: LongWord): LongWord; stdcall; external RTC5DLL;
function  get_serial_number(): LongWord; stdcall; external RTC5DLL;
function  get_hex_version(): LongWord; stdcall; external RTC5DLL;
function  get_rtc_version(): LongWord; stdcall; external RTC5DLL;
function  n_load_program_file(CardNo: LongWord; Path: PChar): LongWord; stdcall; external RTC5DLL;
procedure n_sync_slaves(CardNo: LongWord); stdcall; external RTC5DLL;
function  n_load_correction_file(CardNo: LongWord; Name: PChar; No: LongWord; Dim: LongWord): LongWord; stdcall; external RTC5DLL;
function  n_load_z_table(CardNo: LongWord; A: Double; B: Double; C: Double): LongWord; stdcall; external RTC5DLL;
procedure n_select_cor_table(CardNo: LongWord; HeadA: LongWord; HeadB: LongWord); stdcall; external RTC5DLL;
function  n_set_dsp_mode(CardNo: LongWord; Mode: LongWord): LongWord; stdcall; external RTC5DLL;
function  n_get_head_para(CardNo: LongWord; HeadNo: LongWord; ParaNo: LongWord): Double; stdcall; external RTC5DLL;
function  n_get_table_para(CardNo: LongWord; TableNo: LongWord; ParaNo: LongWord): Double; stdcall; external RTC5DLL;
function  load_program_file(Path: PChar): LongWord; stdcall; external RTC5DLL;
procedure sync_slaves(); stdcall; external RTC5DLL;
function  load_correction_file(Name: PChar; No: LongWord; Dim: LongWord): LongWord; stdcall; external RTC5DLL;
function  load_z_table(A: Double; B: Double; C: Double): LongWord; stdcall; external RTC5DLL;
procedure select_cor_table(HeadA: LongWord; HeadB: LongWord); stdcall; external RTC5DLL;
function  set_dsp_mode(Mode: LongWord): LongWord; stdcall; external RTC5DLL;
function  get_head_para(HeadNo: LongWord; ParaNo: LongWord): Double; stdcall; external RTC5DLL;
function  get_table_para(TableNo: LongWord; ParaNo: LongWord): Double; stdcall; external RTC5DLL;
procedure n_config_list(CardNo: LongWord; Mem1: LongWord; Mem2: LongWord); stdcall; external RTC5DLL;
procedure n_get_config_list(CardNo: LongWord); stdcall; external RTC5DLL;
function  n_save_disk(CardNo: LongWord; Name: PChar; Mode: LongWord): LongWord; stdcall; external RTC5DLL;
function  n_load_disk(CardNo: LongWord; Name: PChar; Mode: LongWord): LongWord; stdcall; external RTC5DLL;
function  n_get_list_space(CardNo: LongWord): LongWord; stdcall; external RTC5DLL;
procedure config_list(Mem1: LongWord; Mem2: LongWord); stdcall; external RTC5DLL;
procedure get_config_list(); stdcall; external RTC5DLL;
function  save_disk(Name: PChar; Mode: LongWord): LongWord; stdcall; external RTC5DLL;
function  load_disk(Name: PChar; Mode: LongWord): LongWord; stdcall; external RTC5DLL;
function  get_list_space(): LongWord; stdcall; external RTC5DLL;
procedure n_set_start_list_pos(CardNo: LongWord; ListNo: LongWord; Pos: LongWord); stdcall; external RTC5DLL;
procedure n_set_start_list(CardNo: LongWord; ListNo: LongWord); stdcall; external RTC5DLL;
procedure n_set_start_list_1(CardNo: LongWord); stdcall; external RTC5DLL;
procedure n_set_start_list_2(CardNo: LongWord); stdcall; external RTC5DLL;
procedure n_set_input_pointer(CardNo: LongWord; Pos: LongWord); stdcall; external RTC5DLL;
function  n_load_list(CardNo: LongWord; ListNo: LongWord; Pos: LongWord): LongWord; stdcall; external RTC5DLL;
procedure n_load_sub(CardNo: LongWord; Index: LongWord); stdcall; external RTC5DLL;
procedure n_load_char(CardNo: LongWord; Char: LongWord); stdcall; external RTC5DLL;
procedure n_load_text_table(CardNo: LongWord; Index: LongWord); stdcall; external RTC5DLL;
procedure n_get_list_pointer(CardNo: LongWord; var ListNo: LongWord; var Pos: LongWord); stdcall; external RTC5DLL;
function  n_get_input_pointer(CardNo: LongWord): LongWord; stdcall; external RTC5DLL;
procedure set_start_list_pos(ListNo: LongWord; Pos: LongWord); stdcall; external RTC5DLL;
procedure set_start_list(ListNo: LongWord); stdcall; external RTC5DLL;
procedure set_start_list_1(); stdcall; external RTC5DLL;
procedure set_start_list_2(); stdcall; external RTC5DLL;
procedure set_input_pointer(Pos: LongWord); stdcall; external RTC5DLL;
function  load_list(ListNo: LongWord; Pos: LongWord): LongWord; stdcall; external RTC5DLL;
procedure load_sub(Index: LongWord); stdcall; external RTC5DLL;
procedure load_char(Char: LongWord); stdcall; external RTC5DLL;
procedure load_text_table(Index: LongWord); stdcall; external RTC5DLL;
procedure get_list_pointer(var ListNo: LongWord; var Pos: LongWord); stdcall; external RTC5DLL;
function  get_input_pointer(): LongWord; stdcall; external RTC5DLL;
procedure n_execute_list_pos(CardNo: LongWord; ListNo: LongWord; Pos: LongWord); stdcall; external RTC5DLL;
procedure n_execute_at_pointer(CardNo: LongWord; Pos: LongWord); stdcall; external RTC5DLL;
procedure n_execute_list(CardNo: LongWord; ListNo: LongWord); stdcall; external RTC5DLL;
procedure n_execute_list_1(CardNo: LongWord); stdcall; external RTC5DLL;
procedure n_execute_list_2(CardNo: LongWord); stdcall; external RTC5DLL;
procedure n_get_out_pointer(CardNo: LongWord; var ListNo: LongWord; var Pos: LongWord); stdcall; external RTC5DLL;
procedure execute_list_pos(ListNo: LongWord; Pos: LongWord); stdcall; external RTC5DLL;
procedure execute_at_pointer(Pos: LongWord); stdcall; external RTC5DLL;
procedure execute_list(ListNo: LongWord); stdcall; external RTC5DLL;
procedure execute_list_1(); stdcall; external RTC5DLL;
procedure execute_list_2(); stdcall; external RTC5DLL;
procedure get_out_pointer(var ListNo: LongWord; var Pos: LongWord); stdcall; external RTC5DLL;
procedure n_auto_change_pos(CardNo: LongWord; Pos: LongWord); stdcall; external RTC5DLL;
procedure n_start_loop(CardNo: LongWord); stdcall; external RTC5DLL;
procedure n_quit_loop(CardNo: LongWord); stdcall; external RTC5DLL;
procedure n_pause_list(CardNo: LongWord); stdcall; external RTC5DLL;
procedure n_restart_list(CardNo: LongWord); stdcall; external RTC5DLL;
procedure n_release_wait(CardNo: LongWord); stdcall; external RTC5DLL;
procedure n_stop_execution(CardNo: LongWord); stdcall; external RTC5DLL;
procedure n_auto_change(CardNo: LongWord); stdcall; external RTC5DLL;
procedure n_stop_list(CardNo: LongWord); stdcall; external RTC5DLL;
function  n_get_wait_status(CardNo: LongWord): LongWord; stdcall; external RTC5DLL;
function  n_read_status(CardNo: LongWord): LongWord; stdcall; external RTC5DLL;
procedure n_get_status(CardNo: LongWord; var Status: LongWord; var Pos: LongWord); stdcall; external RTC5DLL;
procedure auto_change_pos(Pos: LongWord); stdcall; external RTC5DLL;
procedure start_loop(); stdcall; external RTC5DLL;
procedure quit_loop(); stdcall; external RTC5DLL;
procedure pause_list(); stdcall; external RTC5DLL;
procedure restart_list(); stdcall; external RTC5DLL;
procedure release_wait(); stdcall; external RTC5DLL;
procedure stop_execution(); stdcall; external RTC5DLL;
procedure auto_change(); stdcall; external RTC5DLL;
procedure stop_list(); stdcall; external RTC5DLL;
function  get_wait_status(): LongWord; stdcall; external RTC5DLL;
function  read_status(): LongWord; stdcall; external RTC5DLL;
procedure get_status(var Status: LongWord; var Pos: LongWord); stdcall; external RTC5DLL;
procedure n_set_extstartpos(CardNo: LongWord; Pos: LongWord); stdcall; external RTC5DLL;
procedure n_set_max_counts(CardNo: LongWord; Counts: LongWord); stdcall; external RTC5DLL;
procedure n_set_control_mode(CardNo: LongWord; Mode: LongWord); stdcall; external RTC5DLL;
procedure n_simulate_ext_stop(CardNo: LongWord); stdcall; external RTC5DLL;
procedure n_simulate_ext_start_ctrl(CardNo: LongWord); stdcall; external RTC5DLL;
function  n_get_counts(CardNo: LongWord): LongWord; stdcall; external RTC5DLL;
function  n_get_startstop_info(CardNo: LongWord): LongWord; stdcall; external RTC5DLL;
procedure set_extstartpos(Pos: LongWord); stdcall; external RTC5DLL;
procedure set_max_counts(Counts: LongWord); stdcall; external RTC5DLL;
procedure set_control_mode(Mode: LongWord); stdcall; external RTC5DLL;
procedure simulate_ext_stop(); stdcall; external RTC5DLL;
procedure simulate_ext_start_ctrl(); stdcall; external RTC5DLL;
function  get_counts(): LongWord; stdcall; external RTC5DLL;
function  get_startstop_info(): LongWord; stdcall; external RTC5DLL;
procedure n_copy_dst_src(CardNo: LongWord; Dst: LongWord; Src: LongWord; Mode: LongWord); stdcall; external RTC5DLL;
procedure n_set_char_pointer(CardNo: LongWord; Char: LongWord; Pos: LongWord); stdcall; external RTC5DLL;
procedure n_set_sub_pointer(CardNo: LongWord; Index: LongWord; Pos: LongWord); stdcall; external RTC5DLL;
procedure n_set_text_table_pointer(CardNo: LongWord; Index: LongWord; Pos: LongWord); stdcall; external RTC5DLL;
procedure n_set_char_table(CardNo: LongWord; Index: LongWord; Pos: LongWord); stdcall; external RTC5DLL;
function  n_get_char_pointer(CardNo: LongWord; Char: LongWord): LongWord; stdcall; external RTC5DLL;
function  n_get_sub_pointer(CardNo: LongWord; Index: LongWord): LongWord; stdcall; external RTC5DLL;
function  n_get_text_table_pointer(CardNo: LongWord; Index: LongWord): LongWord; stdcall; external RTC5DLL;
procedure copy_dst_src(Dst: LongWord; Src: LongWord; Mode: LongWord); stdcall; external RTC5DLL;
procedure set_char_pointer(Char: LongWord; Pos: LongWord); stdcall; external RTC5DLL;
procedure set_sub_pointer(Index: LongWord; Pos: LongWord); stdcall; external RTC5DLL;
procedure set_text_table_pointer(Index: LongWord; Pos: LongWord); stdcall; external RTC5DLL;
procedure set_char_table(Index: LongWord; Pos: LongWord); stdcall; external RTC5DLL;
function  get_char_pointer(Char: LongWord): LongWord; stdcall; external RTC5DLL;
function  get_sub_pointer(Index: LongWord): LongWord; stdcall; external RTC5DLL;
function  get_text_table_pointer(Index: LongWord): LongWord; stdcall; external RTC5DLL;
procedure n_time_update(CardNo: LongWord); stdcall; external RTC5DLL;
procedure n_set_serial_step(CardNo: LongWord; No: LongWord; Step: LongWord); stdcall; external RTC5DLL;
procedure n_set_serial(CardNo: LongWord; No: LongWord); stdcall; external RTC5DLL;
function  n_get_serial(CardNo: LongWord): Double; stdcall; external RTC5DLL;
procedure time_update(); stdcall; external RTC5DLL;
procedure set_serial_step(No: LongWord; Step: LongWord); stdcall; external RTC5DLL;
procedure set_serial(No: LongWord); stdcall; external RTC5DLL;
function  get_serial(): Double; stdcall; external RTC5DLL;
procedure n_write_io_port_mask(CardNo: LongWord; Value: LongWord; Mask: LongWord); stdcall; external RTC5DLL;
procedure n_write_8bit_port(CardNo: LongWord; Value: LongWord); stdcall; external RTC5DLL;
function  n_read_io_port(CardNo: LongWord): LongWord; stdcall; external RTC5DLL;
function  n_read_io_port_buffer(CardNo: LongWord; Index: LongWord; var Value: LongWord; var XPos: LongInt; var YPos: LongInt; var Time: LongWord): LongWord; stdcall; external RTC5DLL;
function  n_get_io_status(CardNo: LongWord): LongWord; stdcall; external RTC5DLL;
procedure n_write_da_x(CardNo: LongWord; x: LongWord; Value: LongWord); stdcall; external RTC5DLL;
procedure n_set_laser_off_default(CardNo: LongWord; AnalogOut1: LongWord; AnalogOut2: LongWord; DigitalOut: LongWord); stdcall; external RTC5DLL;
procedure n_set_port_default(CardNo: LongWord; Port: LongWord; Value: LongWord); stdcall; external RTC5DLL;
procedure n_write_io_port(CardNo: LongWord; Value: LongWord); stdcall; external RTC5DLL;
procedure n_write_da_1(CardNo: LongWord; Value: LongWord); stdcall; external RTC5DLL;
procedure n_write_da_2(CardNo: LongWord; Value: LongWord); stdcall; external RTC5DLL;
procedure write_io_port_mask(Value: LongWord; Mask: LongWord); stdcall; external RTC5DLL;
procedure write_8bit_port(Value: LongWord); stdcall; external RTC5DLL;
function  read_io_port(): LongWord; stdcall; external RTC5DLL;
function  read_io_port_buffer(Index: LongWord; var Value: LongWord; var XPos: LongInt; var YPos: LongInt; var Time: LongWord): LongWord; stdcall; external RTC5DLL;
function  get_io_status(): LongWord; stdcall; external RTC5DLL;
procedure write_da_x(x: LongWord; Value: LongWord); stdcall; external RTC5DLL;
procedure set_laser_off_default(AnalogOut1: LongWord; AnalogOut2: LongWord; DigitalOut: LongWord); stdcall; external RTC5DLL;
procedure set_port_default(Port: LongWord; Value: LongWord); stdcall; external RTC5DLL;
procedure write_io_port(Value: LongWord); stdcall; external RTC5DLL;
procedure write_da_1(Value: LongWord); stdcall; external RTC5DLL;
procedure write_da_2(Value: LongWord); stdcall; external RTC5DLL;
procedure n_disable_laser(CardNo: LongWord); stdcall; external RTC5DLL;
procedure n_enable_laser(CardNo: LongWord); stdcall; external RTC5DLL;
procedure n_laser_signal_on(CardNo: LongWord); stdcall; external RTC5DLL;
procedure n_laser_signal_off(CardNo: LongWord); stdcall; external RTC5DLL;
procedure n_set_standby(CardNo: LongWord; HalfPeriod: LongWord; PulseLength: LongWord); stdcall; external RTC5DLL;
procedure n_set_laser_pulses_ctrl(CardNo: LongWord; HalfPeriod: LongWord; PulseLength: LongWord); stdcall; external RTC5DLL;
procedure n_set_firstpulse_killer(CardNo: LongWord; Length: LongWord); stdcall; external RTC5DLL;
procedure n_set_qswitch_delay(CardNo: LongWord; Delay: LongWord); stdcall; external RTC5DLL;
procedure n_set_laser_mode(CardNo: LongWord; Mode: LongWord); stdcall; external RTC5DLL;
procedure n_set_laser_control(CardNo: LongWord; Ctrl: LongWord); stdcall; external RTC5DLL;
procedure n_set_laser_pin_out(CardNo: LongWord; Pins: LongWord); stdcall; external RTC5DLL;
function  n_get_laser_pin_in(CardNo: LongWord): LongWord; stdcall; external RTC5DLL;
procedure n_set_softstart_level(CardNo: LongWord; Index: LongWord; Level: LongWord); stdcall; external RTC5DLL;
procedure n_set_softstart_mode(CardNo: LongWord; Mode: LongWord; Number: LongWord; Delay: LongWord); stdcall; external RTC5DLL;
function  n_set_auto_laser_control(CardNo: LongWord; Ctrl: LongWord; Value: LongWord; Mode: LongWord; MinValue: LongWord; MaxValue: LongWord): LongWord; stdcall; external RTC5DLL;
function  n_set_auto_laser_params(CardNo: LongWord; Ctrl: LongWord; Value: LongWord; MinValue: LongWord; MaxValue: LongWord): LongWord; stdcall; external RTC5DLL;
function  n_load_auto_laser_control(CardNo: LongWord; Name: PChar; No: LongWord): LongInt; stdcall; external RTC5DLL;
function  n_load_position_control(CardNo: LongWord; Name: PChar; No: LongWord): LongInt; stdcall; external RTC5DLL;
procedure n_set_default_pixel(CardNo: LongWord; PulseLength: LongWord); stdcall; external RTC5DLL;
procedure n_get_standby(CardNo: LongWord; var HalfPeriod: LongWord; var PulseLength: LongWord); stdcall; external RTC5DLL;
procedure disable_laser(); stdcall; external RTC5DLL;
procedure enable_laser(); stdcall; external RTC5DLL;
procedure laser_signal_on(); stdcall; external RTC5DLL;
procedure laser_signal_off(); stdcall; external RTC5DLL;
procedure set_standby(HalfPeriod: LongWord; PulseLength: LongWord); stdcall; external RTC5DLL;
procedure set_laser_pulses_ctrl(HalfPeriod: LongWord; PulseLength: LongWord); stdcall; external RTC5DLL;
procedure set_firstpulse_killer(Length: LongWord); stdcall; external RTC5DLL;
procedure set_qswitch_delay(Delay: LongWord); stdcall; external RTC5DLL;
procedure set_laser_mode(Mode: LongWord); stdcall; external RTC5DLL;
procedure set_laser_control(Ctrl: LongWord); stdcall; external RTC5DLL;
procedure set_laser_pin_out(Pins: LongWord); stdcall; external RTC5DLL;
function  get_laser_pin_in(): LongWord; stdcall; external RTC5DLL;
procedure set_softstart_level(Index: LongWord; Level: LongWord); stdcall; external RTC5DLL;
procedure set_softstart_mode(Mode: LongWord; Number: LongWord; Delay: LongWord); stdcall; external RTC5DLL;
function  set_auto_laser_control(Ctrl: LongWord; Value: LongWord; Mode: LongWord; MinValue: LongWord; MaxValue: LongWord): LongWord; stdcall; external RTC5DLL;
function  set_auto_laser_params(Ctrl: LongWord; Value: LongWord; MinValue: LongWord; MaxValue: LongWord): LongWord; stdcall; external RTC5DLL;
function  load_auto_laser_control(Name: PChar; No: LongWord): LongInt; stdcall; external RTC5DLL;
function  load_position_control(Name: PChar; No: LongWord): LongInt; stdcall; external RTC5DLL;
procedure set_default_pixel(PulseLength: LongWord); stdcall; external RTC5DLL;
procedure get_standby(var HalfPeriod: LongWord; var PulseLength: LongWord); stdcall; external RTC5DLL;
procedure n_set_ext_start_delay(CardNo: LongWord; Delay: LongInt; EncoderNo: LongWord); stdcall; external RTC5DLL;
procedure n_set_rot_center(CardNo: LongWord; X: LongInt; Y: LongInt); stdcall; external RTC5DLL;
procedure n_simulate_encoder(CardNo: LongWord; EncoderNo: LongWord); stdcall; external RTC5DLL;
function  n_get_marking_info(CardNo: LongWord): LongWord; stdcall; external RTC5DLL;
procedure n_set_encoder_speed_ctrl(CardNo: LongWord; EncoderNo: LongWord; Speed: Double; Smooth: Double); stdcall; external RTC5DLL;
procedure n_set_mcbsp_x(CardNo: LongWord; ScaleX: Double); stdcall; external RTC5DLL;
procedure n_set_mcbsp_y(CardNo: LongWord; ScaleY: Double); stdcall; external RTC5DLL;
procedure n_set_mcbsp_rot(CardNo: LongWord; Resolution: Double); stdcall; external RTC5DLL;
procedure n_get_encoder(CardNo: LongWord; var Encoder0: LongInt; var Encoder1: LongInt); stdcall; external RTC5DLL;
procedure n_read_encoder(CardNo: LongWord; var Encoder0_1: LongInt; var Encoder1_1: LongInt; var Encoder0_2: LongInt; var Encoder1_2: LongInt); stdcall; external RTC5DLL;
function  n_get_mcbsp(CardNo: LongWord): LongInt; stdcall; external RTC5DLL;
function  n_read_mcbsp(CardNo: LongWord; No: LongWord): LongInt; stdcall; external RTC5DLL;
procedure set_ext_start_delay(Delay: LongInt; EncoderNo: LongWord); stdcall; external RTC5DLL;
procedure set_rot_center(X: LongInt; Y: LongInt); stdcall; external RTC5DLL;
procedure simulate_encoder(EncoderNo: LongWord); stdcall; external RTC5DLL;
function  get_marking_info(): LongWord; stdcall; external RTC5DLL;
procedure set_encoder_speed_ctrl(EncoderNo: LongWord; Speed: Double; Smooth: Double); stdcall; external RTC5DLL;
procedure set_mcbsp_x(ScaleX: Double); stdcall; external RTC5DLL;
procedure set_mcbsp_y(ScaleY: Double); stdcall; external RTC5DLL;
procedure set_mcbsp_rot(Resolution: Double); stdcall; external RTC5DLL;
procedure get_encoder(var Encoder0: LongInt; var Encoder1: LongInt); stdcall; external RTC5DLL;
procedure read_encoder(var Encoder0_1: LongInt; var Encoder1_1: LongInt; var Encoder0_2: LongInt; var Encoder1_2: LongInt); stdcall; external RTC5DLL;
function  get_mcbsp(): LongInt; stdcall; external RTC5DLL;
function  read_mcbsp(No: LongWord): LongInt; stdcall; external RTC5DLL;
function  n_get_time(CardNo: LongWord): Double; stdcall; external RTC5DLL;
procedure n_measurement_status(CardNo: LongWord; var Busy: LongWord; var Pos: LongWord); stdcall; external RTC5DLL;
procedure n_get_waveform(CardNo: LongWord; Channel: LongWord; Number: LongWord; Ptr: PLongInt); stdcall; external RTC5DLL;
procedure n_bounce_supp(CardNo: LongWord; Length: LongWord); stdcall; external RTC5DLL;
procedure n_home_position_xyz(CardNo: LongWord; XHome: LongInt; YHome: LongInt; ZHome: LongInt); stdcall; external RTC5DLL;
procedure n_home_position(CardNo: LongWord; XHome: LongInt; YHome: LongInt); stdcall; external RTC5DLL;
procedure n_rs232_config(CardNo: LongWord; BaudRate: LongWord); stdcall; external RTC5DLL;
procedure n_rs232_write_data(CardNo: LongWord; Data: LongWord); stdcall; external RTC5DLL;
procedure n_rs232_write_text(CardNo: LongWord; pData: PChar); stdcall; external RTC5DLL;
function  n_rs232_read_data(CardNo: LongWord): LongWord; stdcall; external RTC5DLL;
procedure n_mcbsp_init(CardNo: LongWord; XDelay: LongWord; RDelay: LongWord); stdcall; external RTC5DLL;
function  n_get_overrun(CardNo: LongWord): LongWord; stdcall; external RTC5DLL;
function  n_get_master_slave(CardNo: LongWord): LongWord; stdcall; external RTC5DLL;
procedure n_get_transform(CardNo: LongWord; Number: LongWord; Ptr1: PLongInt; Ptr2: PLongInt; Ptr: PLongWord; Code: LongWord); stdcall; external RTC5DLL;
procedure n_stop_trigger(CardNo: LongWord); stdcall; external RTC5DLL;
procedure n_move_to(CardNo: LongWord; Pos: LongWord); stdcall; external RTC5DLL;
function  get_time(): Double; stdcall; external RTC5DLL;
procedure measurement_status(var Busy: LongWord; var Pos: LongWord); stdcall; external RTC5DLL;
procedure get_waveform(Channel: LongWord; Number: LongWord; Ptr: PLongInt); stdcall; external RTC5DLL;
procedure bounce_supp(Length: LongWord); stdcall; external RTC5DLL;
procedure home_position_xyz(XHome: LongInt; YHome: LongInt; ZHome: LongInt); stdcall; external RTC5DLL;
procedure home_position(XHome: LongInt; YHome: LongInt); stdcall; external RTC5DLL;
procedure rs232_config(BaudRate: LongWord); stdcall; external RTC5DLL;
procedure rs232_write_data(Data: LongWord); stdcall; external RTC5DLL;
procedure rs232_write_text(pData: PChar); stdcall; external RTC5DLL;
function  rs232_read_data(): LongWord; stdcall; external RTC5DLL;
procedure mcbsp_init(XDelay: LongWord; RDelay: LongWord); stdcall; external RTC5DLL;
function  get_overrun(): LongWord; stdcall; external RTC5DLL;
function  get_master_slave(): LongWord; stdcall; external RTC5DLL;
procedure get_transform(Number: LongWord; Ptr1: PLongInt; Ptr2: PLongInt; Ptr: PLongWord; Code: LongWord); stdcall; external RTC5DLL;
procedure stop_trigger(); stdcall; external RTC5DLL;
procedure move_to(Pos: LongWord); stdcall; external RTC5DLL;
procedure n_set_defocus(CardNo: LongWord; Shift: LongInt); stdcall; external RTC5DLL;
procedure n_goto_xyz(CardNo: LongWord; X: LongInt; Y: LongInt; Z: LongInt); stdcall; external RTC5DLL;
procedure n_goto_xy(CardNo: LongWord; X: LongInt; Y: LongInt); stdcall; external RTC5DLL;
function  n_get_z_distance(CardNo: LongWord; X: LongInt; Y: LongInt; Z: LongInt): LongInt; stdcall; external RTC5DLL;
procedure set_defocus(Shift: LongInt); stdcall; external RTC5DLL;
procedure goto_xyz(X: LongInt; Y: LongInt; Z: LongInt); stdcall; external RTC5DLL;
procedure goto_xy(X: LongInt; Y: LongInt); stdcall; external RTC5DLL;
function  get_z_distance(X: LongInt; Y: LongInt; Z: LongInt): LongInt; stdcall; external RTC5DLL;
procedure n_set_offset_xyz(CardNo: LongWord; HeadNo: LongWord; XOffset: LongInt; YOffset: LongInt; ZOffset: LongInt; at_once: LongWord); stdcall; external RTC5DLL;
procedure n_set_offset(CardNo: LongWord; HeadNo: LongWord; XOffset: LongInt; YOffset: LongInt; at_once: LongWord); stdcall; external RTC5DLL;
procedure n_set_matrix(CardNo: LongWord; HeadNo: LongWord; M11: Double; M12: Double; M21: Double; M22: Double; at_once: LongWord); stdcall; external RTC5DLL;
procedure n_set_angle(CardNo: LongWord; HeadNo: LongWord; Angle: Double; at_once: LongWord); stdcall; external RTC5DLL;
procedure n_set_scale(CardNo: LongWord; HeadNo: LongWord; Scale: Double; at_once: LongWord); stdcall; external RTC5DLL;
procedure n_apply_mcbsp(CardNo: LongWord; HeadNo: LongWord; at_once: LongWord); stdcall; external RTC5DLL;
function  n_upload_transform(CardNo: LongWord; HeadNo: LongWord; Ptr: PLongWord): LongWord; stdcall; external RTC5DLL;
procedure set_offset_xyz(HeadNo: LongWord; XOffset: LongInt; YOffset: LongInt; ZOffset: LongInt; at_once: LongWord); stdcall; external RTC5DLL;
procedure set_offset(HeadNo: LongWord; XOffset: LongInt; YOffset: LongInt; at_once: LongWord); stdcall; external RTC5DLL;
procedure set_matrix(HeadNo: LongWord; M11: Double; M12: Double; M21: Double; M22: Double; at_once: LongWord); stdcall; external RTC5DLL;
procedure set_angle(HeadNo: LongWord; Angle: Double; at_once: LongWord); stdcall; external RTC5DLL;
procedure set_scale(HeadNo: LongWord; Scale: Double; at_once: LongWord); stdcall; external RTC5DLL;
procedure apply_mcbsp(HeadNo: LongWord; at_once: LongWord); stdcall; external RTC5DLL;
function  upload_transform(HeadNo: LongWord; Ptr: PLongWord): LongWord; stdcall; external RTC5DLL;
function  transform(var Sig1: LongInt; var Sig2: LongInt; Ptr: PLongWord; Code: LongWord): LongWord; stdcall; external RTC5DLL;
procedure n_set_delay_mode(CardNo: LongWord; VarPoly: LongWord; DirectMove3D: LongWord; EdgeLevel: LongWord; MinJumpDelay: LongWord; JumpLengthLimit: LongWord); stdcall; external RTC5DLL;
procedure n_set_jump_speed_ctrl(CardNo: LongWord; Speed: Double); stdcall; external RTC5DLL;
procedure n_set_mark_speed_ctrl(CardNo: LongWord; Speed: Double); stdcall; external RTC5DLL;
procedure n_set_sky_writing_para(CardNo: LongWord; Timelag: Double; LaserOnShift: LongInt; Nprev: LongWord; Npost: LongWord); stdcall; external RTC5DLL;
function  n_load_varpolydelay(CardNo: LongWord; Name: PChar; No: LongWord): LongInt; stdcall; external RTC5DLL;
procedure n_set_hi(CardNo: LongWord; HeadNo: LongWord; GalvoGainX: Double; GalvoGainY: Double; GalvoOffsetX: LongInt; GalvoOffsetY: LongInt); stdcall; external RTC5DLL;
procedure n_get_hi_pos(CardNo: LongWord; HeadNo: LongWord; var X1: LongInt; var X2: LongInt; var Y1: LongInt; var Y2: LongInt); stdcall; external RTC5DLL;
function  n_auto_cal(CardNo: LongWord; HeadNo: LongWord; Command: LongWord): LongWord; stdcall; external RTC5DLL;
function  n_get_auto_cal(CardNo: LongWord; HeadNo: LongWord): LongWord; stdcall; external RTC5DLL;
procedure n_set_sky_writing(CardNo: LongWord; Timelag: Double; LaserOnShift: LongInt); stdcall; external RTC5DLL;
procedure n_get_hi_data(CardNo: LongWord; var X1: LongInt; var X2: LongInt; var Y1: LongInt; var Y2: LongInt); stdcall; external RTC5DLL;
procedure set_delay_mode(VarPoly: LongWord; DirectMove3D: LongWord; EdgeLevel: LongWord; MinJumpDelay: LongWord; JumpLengthLimit: LongWord); stdcall; external RTC5DLL;
procedure set_jump_speed_ctrl(Speed: Double); stdcall; external RTC5DLL;
procedure set_mark_speed_ctrl(Speed: Double); stdcall; external RTC5DLL;
procedure set_sky_writing_para(Timelag: Double; LaserOnShift: LongInt; Nprev: LongWord; Npost: LongWord); stdcall; external RTC5DLL;
function  load_varpolydelay(Name: PChar; No: LongWord): LongInt; stdcall; external RTC5DLL;
procedure set_hi(HeadNo: LongWord; GalvoGainX: Double; GalvoGainY: Double; GalvoOffsetX: LongInt; GalvoOffsetY: LongInt); stdcall; external RTC5DLL;
procedure get_hi_pos(HeadNo: LongWord; var X1: LongInt; var X2: LongInt; var Y1: LongInt; var Y2: LongInt); stdcall; external RTC5DLL;
function  auto_cal(HeadNo: LongWord; Command: LongWord): LongWord; stdcall; external RTC5DLL;
function  get_auto_cal(HeadNo: LongWord): LongWord; stdcall; external RTC5DLL;
procedure set_sky_writing(Timelag: Double; LaserOnShift: LongInt); stdcall; external RTC5DLL;
procedure get_hi_data(var X1: LongInt; var X2: LongInt; var Y1: LongInt; var Y2: LongInt); stdcall; external RTC5DLL;
procedure n_send_user_data(CardNo: LongWord; Head: LongWord; Axis: LongWord; Data0: LongInt; Data1: LongInt; Data2: LongInt; Data3: LongInt; Data4: LongInt); stdcall; external RTC5DLL;
function  n_read_user_data(CardNo: LongWord; Head: LongWord; Axis: LongWord; var Data0: LongInt; var Data1: LongInt; var Data2: LongInt; var Data3: LongInt; var Data4: LongInt): LongInt; stdcall; external RTC5DLL;
procedure n_control_command(CardNo: LongWord; Head: LongWord; Axis: LongWord; Data: LongWord); stdcall; external RTC5DLL;
function  n_get_value(CardNo: LongWord; Signal: LongWord): LongInt; stdcall; external RTC5DLL;
procedure n_get_values(CardNo: LongWord; SignalPtr: PLongWord; ResultPtr: PLongInt); stdcall; external RTC5DLL;
function  n_get_head_status(CardNo: LongWord; Head: LongWord): LongWord; stdcall; external RTC5DLL;
function  n_set_jump_tuning(CardNo: LongWord; Flag: LongInt; Length: LongWord; VA1: LongInt; VA2: LongInt; VB1: LongInt; VB2: LongInt; JA1: LongInt; JA2: LongInt; JB1: LongInt; JB2: LongInt): LongInt; stdcall; external RTC5DLL;
function  n_load_jump_table(CardNo: LongWord; Name: PChar; No: LongWord; Ack: LongWord; MinDelay: LongWord; MaxDelay: LongWord; ListPos: LongWord): LongInt; stdcall; external RTC5DLL;
function  n_get_jump_table(CardNo: LongWord; Ptr: PWord): LongWord; stdcall; external RTC5DLL;
function  n_set_jump_table(CardNo: LongWord; Ptr: PWord): LongWord; stdcall; external RTC5DLL;
procedure send_user_data(Head: LongWord; Axis: LongWord; Data0: LongInt; Data1: LongInt; Data2: LongInt; Data3: LongInt; Data4: LongInt); stdcall; external RTC5DLL;
function  read_user_data(Head: LongWord; Axis: LongWord; var Data0: LongInt; var Data1: LongInt; var Data2: LongInt; var Data3: LongInt; var Data4: LongInt): LongInt; stdcall; external RTC5DLL;
procedure control_command(Head: LongWord; Axis: LongWord; Data: LongWord); stdcall; external RTC5DLL;
function  get_value(Signal: LongWord): LongInt; stdcall; external RTC5DLL;
procedure get_values(SignalPtr: PLongWord; ResultPtr: PLongInt); stdcall; external RTC5DLL;
function  get_head_status(Head: LongWord): LongWord; stdcall; external RTC5DLL;
function  set_jump_tuning(Flag: LongInt; Length: LongWord; VA1: LongInt; VA2: LongInt; VB1: LongInt; VB2: LongInt; JA1: LongInt; JA2: LongInt; JB1: LongInt; JB2: LongInt): LongInt; stdcall; external RTC5DLL;
function  load_jump_table(Name: PChar; No: LongWord; Ack: LongWord; MinDelay: LongWord; MaxDelay: LongWord; ListPos: LongWord): LongInt; stdcall; external RTC5DLL;
function  get_jump_table(Ptr: PWord): LongWord; stdcall; external RTC5DLL;
function  set_jump_table(Ptr: PWord): LongWord; stdcall; external RTC5DLL;
procedure n_select_cor_table_list(CardNo: LongWord; HeadA: LongWord; HeadB: LongWord); stdcall; external RTC5DLL;
procedure select_cor_table_list(HeadA: LongWord; HeadB: LongWord); stdcall; external RTC5DLL;
procedure n_list_nop(CardNo: LongWord); stdcall; external RTC5DLL;
procedure n_long_delay(CardNo: LongWord; Delay: LongWord); stdcall; external RTC5DLL;
procedure n_set_end_of_list(CardNo: LongWord); stdcall; external RTC5DLL;
procedure n_set_wait(CardNo: LongWord; WaitWord: LongWord); stdcall; external RTC5DLL;
procedure n_list_jump_pos(CardNo: LongWord; Pos: LongWord); stdcall; external RTC5DLL;
procedure n_list_jump_rel(CardNo: LongWord; Pos: LongInt); stdcall; external RTC5DLL;
procedure n_set_list_jump(CardNo: LongWord; Pos: LongWord); stdcall; external RTC5DLL;
procedure list_nop(); stdcall; external RTC5DLL;
procedure long_delay(Delay: LongWord); stdcall; external RTC5DLL;
procedure set_end_of_list(); stdcall; external RTC5DLL;
procedure set_wait(WaitWord: LongWord); stdcall; external RTC5DLL;
procedure list_jump_pos(Pos: LongWord); stdcall; external RTC5DLL;
procedure list_jump_rel(Pos: LongInt); stdcall; external RTC5DLL;
procedure set_list_jump(Pos: LongWord); stdcall; external RTC5DLL;
procedure n_set_extstartpos_list(CardNo: LongWord; Pos: LongWord); stdcall; external RTC5DLL;
procedure n_set_control_mode_list(CardNo: LongWord; Mode: LongWord); stdcall; external RTC5DLL;
procedure n_simulate_ext_start(CardNo: LongWord; Delay: LongInt; EncoderNo: LongWord); stdcall; external RTC5DLL;
procedure set_extstartpos_list(Pos: LongWord); stdcall; external RTC5DLL;
procedure set_control_mode_list(Mode: LongWord); stdcall; external RTC5DLL;
procedure simulate_ext_start(Delay: LongInt; EncoderNo: LongWord); stdcall; external RTC5DLL;
procedure n_list_return(CardNo: LongWord); stdcall; external RTC5DLL;
procedure n_list_call(CardNo: LongWord; Pos: LongWord); stdcall; external RTC5DLL;
procedure n_list_call_abs(CardNo: LongWord; Pos: LongWord); stdcall; external RTC5DLL;
procedure n_sub_call(CardNo: LongWord; Index: LongWord); stdcall; external RTC5DLL;
procedure n_sub_call_abs(CardNo: LongWord; Index: LongWord); stdcall; external RTC5DLL;
procedure list_return(); stdcall; external RTC5DLL;
procedure list_call(Pos: LongWord); stdcall; external RTC5DLL;
procedure list_call_abs(Pos: LongWord); stdcall; external RTC5DLL;
procedure sub_call(Index: LongWord); stdcall; external RTC5DLL;
procedure sub_call_abs(Index: LongWord); stdcall; external RTC5DLL;
procedure n_list_call_cond(CardNo: LongWord; Mask1: LongWord; Mask0: LongWord; Pos: LongWord); stdcall; external RTC5DLL;
procedure n_list_call_abs_cond(CardNo: LongWord; Mask1: LongWord; Mask0: LongWord; Pos: LongWord); stdcall; external RTC5DLL;
procedure n_sub_call_cond(CardNo: LongWord; Mask1: LongWord; Mask0: LongWord; Pos: LongWord); stdcall; external RTC5DLL;
procedure n_sub_call_abs_cond(CardNo: LongWord; Mask1: LongWord; Mask0: LongWord; Pos: LongWord); stdcall; external RTC5DLL;
procedure n_list_jump_pos_cond(CardNo: LongWord; Mask1: LongWord; Mask0: LongWord; Index: LongWord); stdcall; external RTC5DLL;
procedure n_list_jump_rel_cond(CardNo: LongWord; Mask1: LongWord; Mask0: LongWord; Index: LongInt); stdcall; external RTC5DLL;
procedure n_if_cond(CardNo: LongWord; Mask1: LongWord; Mask0: LongWord); stdcall; external RTC5DLL;
procedure n_if_not_cond(CardNo: LongWord; Mask1: LongWord; Mask0: LongWord); stdcall; external RTC5DLL;
procedure n_if_pin_cond(CardNo: LongWord; Mask1: LongWord; Mask0: LongWord); stdcall; external RTC5DLL;
procedure n_if_not_pin_cond(CardNo: LongWord; Mask1: LongWord; Mask0: LongWord); stdcall; external RTC5DLL;
procedure n_switch_ioport(CardNo: LongWord; MaskBits: LongWord; ShiftBits: LongWord); stdcall; external RTC5DLL;
procedure n_list_jump_cond(CardNo: LongWord; Mask1: LongWord; Mask0: LongWord; Pos: LongWord); stdcall; external RTC5DLL;
procedure list_call_cond(Mask1: LongWord; Mask0: LongWord; Pos: LongWord); stdcall; external RTC5DLL;
procedure list_call_abs_cond(Mask1: LongWord; Mask0: LongWord; Pos: LongWord); stdcall; external RTC5DLL;
procedure sub_call_cond(Mask1: LongWord; Mask0: LongWord; Index: LongWord); stdcall; external RTC5DLL;
procedure sub_call_abs_cond(Mask1: LongWord; Mask0: LongWord; Index: LongWord); stdcall; external RTC5DLL;
procedure list_jump_pos_cond(Mask1: LongWord; Mask0: LongWord; Pos: LongWord); stdcall; external RTC5DLL;
procedure list_jump_rel_cond(Mask1: LongWord; Mask0: LongWord; Pos: LongInt); stdcall; external RTC5DLL;
procedure if_cond(Mask1: LongWord; Mask0: LongWord); stdcall; external RTC5DLL;
procedure if_not_cond(Mask1: LongWord; Mask0: LongWord); stdcall; external RTC5DLL;
procedure if_pin_cond(Mask1: LongWord; Mask0: LongWord); stdcall; external RTC5DLL;
procedure if_not_pin_cond(Mask1: LongWord; Mask0: LongWord); stdcall; external RTC5DLL;
procedure switch_ioport(MaskBits: LongWord; ShiftBits: LongWord); stdcall; external RTC5DLL;
procedure list_jump_cond(Mask1: LongWord; Mask0: LongWord; Pos: LongWord); stdcall; external RTC5DLL;
procedure n_select_char_set(CardNo: LongWord; No: LongWord); stdcall; external RTC5DLL;
procedure n_mark_text(CardNo: LongWord; Text: PChar); stdcall; external RTC5DLL;
procedure n_mark_text_abs(CardNo: LongWord; Text: PChar); stdcall; external RTC5DLL;
procedure n_mark_char(CardNo: LongWord; Char: LongWord); stdcall; external RTC5DLL;
procedure n_mark_char_abs(CardNo: LongWord; Char: LongWord); stdcall; external RTC5DLL;
procedure select_char_set(No: LongWord); stdcall; external RTC5DLL;
procedure mark_text(Text: PChar); stdcall; external RTC5DLL;
procedure mark_text_abs(Text: PChar); stdcall; external RTC5DLL;
procedure mark_char(Char: LongWord); stdcall; external RTC5DLL;
procedure mark_char_abs(Char: LongWord); stdcall; external RTC5DLL;
procedure n_mark_serial(CardNo: LongWord; Mode: LongWord; Digits: LongWord); stdcall; external RTC5DLL;
procedure n_mark_serial_abs(CardNo: LongWord; Mode: LongWord; Digits: LongWord); stdcall; external RTC5DLL;
procedure n_mark_date(CardNo: LongWord; Part: LongWord; Mode: LongWord); stdcall; external RTC5DLL;
procedure n_mark_date_abs(CardNo: LongWord; Part: LongWord; Mode: LongWord); stdcall; external RTC5DLL;
procedure n_mark_time(CardNo: LongWord; Part: LongWord; Mode: LongWord); stdcall; external RTC5DLL;
procedure n_mark_time_abs(CardNo: LongWord; Part: LongWord; Mode: LongWord); stdcall; external RTC5DLL;
procedure n_time_fix_f_off(CardNo: LongWord; FirstDay: LongWord; Offset: LongWord); stdcall; external RTC5DLL;
procedure n_time_fix_f(CardNo: LongWord; FirstDay: LongWord); stdcall; external RTC5DLL;
procedure n_time_fix(CardNo: LongWord); stdcall; external RTC5DLL;
procedure mark_serial(Mode: LongWord; Digits: LongWord); stdcall; external RTC5DLL;
procedure mark_serial_abs(Mode: LongWord; Digits: LongWord); stdcall; external RTC5DLL;
procedure mark_date(Part: LongWord; Mode: LongWord); stdcall; external RTC5DLL;
procedure mark_date_abs(Part: LongWord; Mode: LongWord); stdcall; external RTC5DLL;
procedure mark_time(Part: LongWord; Mode: LongWord); stdcall; external RTC5DLL;
procedure mark_time_abs(Part: LongWord; Mode: LongWord); stdcall; external RTC5DLL;
procedure time_fix_f_off(FirstDay: LongWord; Offset: LongWord); stdcall; external RTC5DLL;
procedure time_fix_f(FirstDay: LongWord); stdcall; external RTC5DLL;
procedure time_fix(); stdcall; external RTC5DLL;
procedure n_clear_io_cond_list(CardNo: LongWord; Mask1: LongWord; Mask0: LongWord; Mask: LongWord); stdcall; external RTC5DLL;
procedure n_set_io_cond_list(CardNo: LongWord; Mask1: LongWord; Mask0: LongWord; Mask: LongWord); stdcall; external RTC5DLL;
procedure n_write_io_port_mask_list(CardNo: LongWord; Value: LongWord; Mask: LongWord); stdcall; external RTC5DLL;
procedure n_write_8bit_port_list(CardNo: LongWord; Value: LongWord); stdcall; external RTC5DLL;
procedure n_read_io_port_list(CardNo: LongWord); stdcall; external RTC5DLL;
procedure n_write_da_x_list(CardNo: LongWord; x: LongWord; Value: LongWord); stdcall; external RTC5DLL;
procedure n_write_io_port_list(CardNo: LongWord; Value: LongWord); stdcall; external RTC5DLL;
procedure n_write_da_1_list(CardNo: LongWord; Value: LongWord); stdcall; external RTC5DLL;
procedure n_write_da_2_list(CardNo: LongWord; Value: LongWord); stdcall; external RTC5DLL;
procedure clear_io_cond_list(Mask1: LongWord; Mask0: LongWord; MaskClear: LongWord); stdcall; external RTC5DLL;
procedure set_io_cond_list(Mask1: LongWord; Mask0: LongWord; MaskSet: LongWord); stdcall; external RTC5DLL;
procedure write_io_port_mask_list(Value: LongWord; Mask: LongWord); stdcall; external RTC5DLL;
procedure write_8bit_port_list(Value: LongWord); stdcall; external RTC5DLL;
procedure read_io_port_list(); stdcall; external RTC5DLL;
procedure write_da_x_list(x: LongWord; Value: LongWord); stdcall; external RTC5DLL;
procedure write_io_port_list(Value: LongWord); stdcall; external RTC5DLL;
procedure write_da_1_list(Value: LongWord); stdcall; external RTC5DLL;
procedure write_da_2_list(Value: LongWord); stdcall; external RTC5DLL;
procedure n_laser_signal_on_list(CardNo: LongWord); stdcall; external RTC5DLL;
procedure n_laser_signal_off_list(CardNo: LongWord); stdcall; external RTC5DLL;
procedure n_para_laser_on_pulses_list(CardNo: LongWord; Period: LongWord; Pulses: LongWord; P: LongWord); stdcall; external RTC5DLL;
procedure n_laser_on_pulses_list(CardNo: LongWord; Period: LongWord; Pulses: LongWord); stdcall; external RTC5DLL;
procedure n_laser_on_list(CardNo: LongWord; Period: LongWord); stdcall; external RTC5DLL;
procedure n_set_laser_delays(CardNo: LongWord; LaserOnDelay: LongInt; LaserOffDelay: LongWord); stdcall; external RTC5DLL;
procedure n_set_standby_list(CardNo: LongWord; HalfPeriod: LongWord; PulseLength: LongWord); stdcall; external RTC5DLL;
procedure n_set_laser_pulses(CardNo: LongWord; HalfPeriod: LongWord; PulseLength: LongWord); stdcall; external RTC5DLL;
procedure n_set_firstpulse_killer_list(CardNo: LongWord; Length: LongWord); stdcall; external RTC5DLL;
procedure n_set_qswitch_delay_list(CardNo: LongWord; Delay: LongWord); stdcall; external RTC5DLL;
procedure n_set_laser_pin_out_list(CardNo: LongWord; Pins: LongWord); stdcall; external RTC5DLL;
procedure n_set_vector_control(CardNo: LongWord; Ctrl: LongWord; Value: LongWord); stdcall; external RTC5DLL;
procedure n_set_default_pixel_list(CardNo: LongWord; PulseLength: LongWord); stdcall; external RTC5DLL;
procedure n_set_auto_laser_params_list(CardNo: LongWord; Ctrl: LongWord; Value: LongWord; MinValue: LongWord; MaxValue: LongWord); stdcall; external RTC5DLL;
procedure n_set_laser_timing(CardNo: LongWord; HalfPeriod: LongWord; PulseLength1: LongWord; PulseLength2: LongWord; TimeBase: LongWord); stdcall; external RTC5DLL;
procedure laser_signal_on_list(); stdcall; external RTC5DLL;
procedure laser_signal_off_list(); stdcall; external RTC5DLL;
procedure para_laser_on_list(Period: LongWord; Pulses: LongWord; P: LongWord); stdcall; external RTC5DLL;
procedure laser_on_pulses_list(Period: LongWord; Pulses: LongWord); stdcall; external RTC5DLL;
procedure laser_on_list(Period: LongWord); stdcall; external RTC5DLL;
procedure set_laser_delays(LaserOnDelay: LongInt; LaserOffDelay: LongWord); stdcall; external RTC5DLL;
procedure set_standby_list(HalfPeriod: LongWord; PulseLength: LongWord); stdcall; external RTC5DLL;
procedure set_laser_pulses(HalfPeriod: LongWord; PulseLength: LongWord); stdcall; external RTC5DLL;
procedure set_firstpulse_killer_list(Length: LongWord); stdcall; external RTC5DLL;
procedure set_qswitch_delay_list(Delay: LongWord); stdcall; external RTC5DLL;
procedure set_laser_pin_out_list(Pins: LongWord); stdcall; external RTC5DLL;
procedure set_vector_control(Ctrl: LongWord; Value: LongWord); stdcall; external RTC5DLL;
procedure set_default_pixel_list(PulseLength: LongWord); stdcall; external RTC5DLL;
procedure set_auto_laser_params_list(Ctrl: LongWord; Value: LongWord; MinValue: LongWord; MaxValue: LongWord); stdcall; external RTC5DLL;
procedure set_laser_timing(HalfPeriod: LongWord; PulseLength1: LongWord; PulseLength2: LongWord; TimeBase: LongWord); stdcall; external RTC5DLL;
procedure n_fly_return(CardNo: LongWord; X: LongInt; Y: LongInt); stdcall; external RTC5DLL;
procedure n_set_rot_center_list(CardNo: LongWord; X: LongInt; Y: LongInt); stdcall; external RTC5DLL;
procedure n_set_ext_start_delay_list(CardNo: LongWord; Delay: LongInt; EncoderNo: LongWord); stdcall; external RTC5DLL;
procedure n_set_fly_x(CardNo: LongWord; ScaleX: Double); stdcall; external RTC5DLL;
procedure n_set_fly_y(CardNo: LongWord; ScaleY: Double); stdcall; external RTC5DLL;
procedure n_set_fly_rot(CardNo: LongWord; Resolution: Double); stdcall; external RTC5DLL;
procedure n_set_fly_x_pos(CardNo: LongWord; ScaleX: Double); stdcall; external RTC5DLL;
procedure n_set_fly_y_pos(CardNo: LongWord; ScaleY: Double); stdcall; external RTC5DLL;
procedure n_set_fly_rot_pos(CardNo: LongWord; Resolution: Double); stdcall; external RTC5DLL;
procedure n_set_mcbsp_x_list(CardNo: LongWord; ScaleX: Double); stdcall; external RTC5DLL;
procedure n_set_mcbsp_y_list(CardNo: LongWord; ScaleY: Double); stdcall; external RTC5DLL;
procedure n_set_mcbsp_rot_list(CardNo: LongWord; Resolution: Double); stdcall; external RTC5DLL;
procedure n_wait_for_encoder_mode(CardNo: LongWord; Value: LongInt; EncoderNo: LongWord; Mode: LongInt); stdcall; external RTC5DLL;
procedure n_wait_for_mcbsp(CardNo: LongWord; Axis: LongWord; Value: LongInt; Mode: LongInt); stdcall; external RTC5DLL;
procedure n_set_encoder_speed(CardNo: LongWord; EncoderNo: LongWord; Speed: Double; Smooth: Double); stdcall; external RTC5DLL;
procedure n_get_mcbsp_list(CardNo: LongWord); stdcall; external RTC5DLL;
procedure n_store_encoder(CardNo: LongWord; Pos: LongWord); stdcall; external RTC5DLL;
procedure n_wait_for_encoder(CardNo: LongWord; Value: LongInt; EncoderNo: LongWord); stdcall; external RTC5DLL;
procedure fly_return(X: LongInt; Y: LongInt); stdcall; external RTC5DLL;
procedure set_rot_center_list(X: LongInt; Y: LongInt); stdcall; external RTC5DLL;
procedure set_ext_start_delay_list(Delay: LongInt; EncoderNo: LongWord); stdcall; external RTC5DLL;
procedure set_fly_x(ScaleX: Double); stdcall; external RTC5DLL;
procedure set_fly_y(ScaleY: Double); stdcall; external RTC5DLL;
procedure set_fly_rot(Resolution: Double); stdcall; external RTC5DLL;
procedure set_fly_x_pos(ScaleX: Double); stdcall; external RTC5DLL;
procedure set_fly_y_pos(ScaleY: Double); stdcall; external RTC5DLL;
procedure set_fly_rot_pos(Resolution: Double); stdcall; external RTC5DLL;
procedure set_mcbsp_x_list(ScaleX: Double); stdcall; external RTC5DLL;
procedure set_mcbsp_y_list(ScaleY: Double); stdcall; external RTC5DLL;
procedure set_mcbsp_rot_list(Resolution: Double); stdcall; external RTC5DLL;
procedure wait_for_encoder_mode(Value: LongInt; EncoderNo: LongWord; Mode: LongInt); stdcall; external RTC5DLL;
procedure wait_for_mcbsp(Axis: LongWord; Value: LongInt; Mode: LongInt); stdcall; external RTC5DLL;
procedure set_encoder_speed(EncoderNo: LongWord; Speed: Double; Smooth: Double); stdcall; external RTC5DLL;
procedure get_mcbsp_list(); stdcall; external RTC5DLL;
procedure store_encoder(Pos: LongWord); stdcall; external RTC5DLL;
procedure wait_for_encoder(Value: LongInt; EncoderNo: LongWord); stdcall; external RTC5DLL;
procedure n_save_and_restart_timer(CardNo: LongWord); stdcall; external RTC5DLL;
procedure n_set_wobbel(CardNo: LongWord; Transversal: LongWord; Longitudinal: LongWord; Freq: Double); stdcall; external RTC5DLL;
procedure n_set_wobbel_mode(CardNo: LongWord; Transversal: LongWord; Longitudinal: LongWord; Freq: Double; Mode: LongInt); stdcall; external RTC5DLL;
procedure n_set_trigger(CardNo: LongWord; Period: LongWord; Signal1: LongWord; Signal2: LongWord); stdcall; external RTC5DLL;
procedure n_set_pixel_line(CardNo: LongWord; Channel: LongWord; HalfPeriod: LongWord; dX: Double; dY: Double); stdcall; external RTC5DLL;
procedure n_set_n_pixel(CardNo: LongWord; PulseLength: LongWord; AnalogOut: LongWord; Number: LongWord); stdcall; external RTC5DLL;
procedure n_set_pixel(CardNo: LongWord; PulseLength: LongWord; AnalogOut: LongWord); stdcall; external RTC5DLL;
procedure n_rs232_write_text_list(CardNo: LongWord; pData: PChar); stdcall; external RTC5DLL;
procedure n_set_mcbsp_out(CardNo: LongWord; Signal1: LongWord; Signal2: LongWord); stdcall; external RTC5DLL;
procedure n_camming(CardNo: LongWord; FirstPos: LongWord; NPos: LongWord; No: LongWord; Ctrl: LongWord; Scale: Double; Code: LongWord); stdcall; external RTC5DLL;
procedure save_and_restart_timer(); stdcall; external RTC5DLL;
procedure set_wobbel(Transversal: LongWord; Longitudinal: LongWord; Freq: Double); stdcall; external RTC5DLL;
procedure set_wobbel_mode(Transversal: LongWord; Longitudinal: LongWord; Freq: Double; Mode: LongInt); stdcall; external RTC5DLL;
procedure set_trigger(Period: LongWord; Signal1: LongWord; Signal2: LongWord); stdcall; external RTC5DLL;
procedure set_pixel_line(Channel: LongWord; HalfPeriod: LongWord; dX: Double; dY: Double); stdcall; external RTC5DLL;
procedure set_n_pixel(PulseLength: LongWord; AnalogOut: LongWord; Number: LongWord); stdcall; external RTC5DLL;
procedure set_pixel(PulseLength: LongWord; AnalogOut: LongWord); stdcall; external RTC5DLL;
procedure rs232_write_text_list(pData: PChar); stdcall; external RTC5DLL;
procedure set_mcbsp_out(Signal1: LongWord; Signal2: LongWord); stdcall; external RTC5DLL;
procedure camming(FirstPos: LongWord; NPos: LongWord; No: LongWord; Ctrl: LongWord; Scale: Double; Code: LongWord); stdcall; external RTC5DLL;
procedure n_timed_mark_abs_3d(CardNo: LongWord; X: LongInt; Y: LongInt; Z: LongInt; T: Double); stdcall; external RTC5DLL;
procedure n_timed_mark_rel_3d(CardNo: LongWord; dX: LongInt; dY: LongInt; dZ: LongInt; T: Double); stdcall; external RTC5DLL;
procedure n_timed_mark_abs(CardNo: LongWord; X: LongInt; Y: LongInt; T: Double); stdcall; external RTC5DLL;
procedure n_timed_mark_rel(CardNo: LongWord; dX: LongInt; dY: LongInt; T: Double); stdcall; external RTC5DLL;
procedure timed_mark_abs_3d(X: LongInt; Y: LongInt; Z: LongInt; T: Double); stdcall; external RTC5DLL;
procedure timed_mark_rel_3d(dX: LongInt; dY: LongInt; dZ: LongInt; T: Double); stdcall; external RTC5DLL;
procedure timed_mark_abs(X: LongInt; Y: LongInt; T: Double); stdcall; external RTC5DLL;
procedure timed_mark_rel(dX: LongInt; dY: LongInt; T: Double); stdcall; external RTC5DLL;
procedure n_mark_abs_3d(CardNo: LongWord; X: LongInt; Y: LongInt; Z: LongInt); stdcall; external RTC5DLL;
procedure n_mark_rel_3d(CardNo: LongWord; dX: LongInt; dY: LongInt; dZ: LongInt); stdcall; external RTC5DLL;
procedure n_mark_abs(CardNo: LongWord; X: LongInt; Y: LongInt); stdcall; external RTC5DLL;
procedure n_mark_rel(CardNo: LongWord; dX: LongInt; dY: LongInt); stdcall; external RTC5DLL;
procedure mark_abs_3d(X: LongInt; Y: LongInt; Z: LongInt); stdcall; external RTC5DLL;
procedure mark_rel_3d(dX: LongInt; dY: LongInt; dZ: LongInt); stdcall; external RTC5DLL;
procedure mark_abs(X: LongInt; Y: LongInt); stdcall; external RTC5DLL;
procedure mark_rel(dX: LongInt; dY: LongInt); stdcall; external RTC5DLL;
procedure n_timed_jump_abs_3d(CardNo: LongWord; X: LongInt; Y: LongInt; Z: LongInt; T: Double); stdcall; external RTC5DLL;
procedure n_timed_jump_rel_3d(CardNo: LongWord; dX: LongInt; dY: LongInt; dZ: LongInt; T: Double); stdcall; external RTC5DLL;
procedure n_timed_jump_abs(CardNo: LongWord; X: LongInt; Y: LongInt; T: Double); stdcall; external RTC5DLL;
procedure n_timed_jump_rel(CardNo: LongWord; dX: LongInt; dY: LongInt; T: Double); stdcall; external RTC5DLL;
procedure timed_jump_abs_3d(X: LongInt; Y: LongInt; Z: LongInt; T: Double); stdcall; external RTC5DLL;
procedure timed_jump_rel_3d(dX: LongInt; dY: LongInt; dZ: LongInt; T: Double); stdcall; external RTC5DLL;
procedure timed_jump_abs(X: LongInt; Y: LongInt; T: Double); stdcall; external RTC5DLL;
procedure timed_jump_rel(dX: LongInt; dY: LongInt; T: Double); stdcall; external RTC5DLL;
procedure n_jump_abs_3d(CardNo: LongWord; X: LongInt; Y: LongInt; Z: LongInt); stdcall; external RTC5DLL;
procedure n_jump_rel_3d(CardNo: LongWord; dX: LongInt; dY: LongInt; dZ: LongInt); stdcall; external RTC5DLL;
procedure n_jump_abs(CardNo: LongWord; X: LongInt; Y: LongInt); stdcall; external RTC5DLL;
procedure n_jump_rel(CardNo: LongWord; dX: LongInt; dY: LongInt); stdcall; external RTC5DLL;
procedure jump_abs_3d(X: LongInt; Y: LongInt; Z: LongInt); stdcall; external RTC5DLL;
procedure jump_rel_3d(dX: LongInt; dY: LongInt; dZ: LongInt); stdcall; external RTC5DLL;
procedure jump_abs(X: LongInt; Y: LongInt); stdcall; external RTC5DLL;
procedure jump_rel(dX: LongInt; dY: LongInt); stdcall; external RTC5DLL;
procedure n_para_mark_abs_3d(CardNo: LongWord; X: LongInt; Y: LongInt; Z: LongInt; P: LongWord); stdcall; external RTC5DLL;
procedure n_para_mark_rel_3d(CardNo: LongWord; dX: LongInt; dY: LongInt; dZ: LongInt; P: LongWord); stdcall; external RTC5DLL;
procedure n_para_mark_abs(CardNo: LongWord; X: LongInt; Y: LongInt; P: LongWord); stdcall; external RTC5DLL;
procedure n_para_mark_rel(CardNo: LongWord; dX: LongInt; dY: LongInt; P: LongWord); stdcall; external RTC5DLL;
procedure para_mark_abs_3d(X: LongInt; Y: LongInt; Z: LongInt; P: LongWord); stdcall; external RTC5DLL;
procedure para_mark_rel_3d(dX: LongInt; dY: LongInt; dZ: LongInt; P: LongWord); stdcall; external RTC5DLL;
procedure para_mark_abs(X: LongInt; Y: LongInt; P: LongWord); stdcall; external RTC5DLL;
procedure para_mark_rel(dX: LongInt; dY: LongInt; P: LongWord); stdcall; external RTC5DLL;
procedure n_para_jump_abs_3d(CardNo: LongWord; X: LongInt; Y: LongInt; Z: LongInt; P: LongWord); stdcall; external RTC5DLL;
procedure n_para_jump_rel_3d(CardNo: LongWord; dX: LongInt; dY: LongInt; dZ: LongInt; P: LongWord); stdcall; external RTC5DLL;
procedure n_para_jump_abs(CardNo: LongWord; X: LongInt; Y: LongInt; P: LongWord); stdcall; external RTC5DLL;
procedure n_para_jump_rel(CardNo: LongWord; dX: LongInt; dY: LongInt; P: LongWord); stdcall; external RTC5DLL;
procedure para_jump_abs_3d(X: LongInt; Y: LongInt; Z: LongInt; P: LongWord); stdcall; external RTC5DLL;
procedure para_jump_rel_3d(dX: LongInt; dY: LongInt; dZ: LongInt; P: LongWord); stdcall; external RTC5DLL;
procedure para_jump_abs(X: LongInt; Y: LongInt; P: LongWord); stdcall; external RTC5DLL;
procedure para_jump_rel(dX: LongInt; dY: LongInt; P: LongWord); stdcall; external RTC5DLL;
procedure n_timed_para_mark_abs_3d(CardNo: LongWord; X: LongInt; Y: LongInt; Z: LongInt; P: LongWord; T: Double); stdcall; external RTC5DLL;
procedure n_timed_para_mark_rel_3d(CardNo: LongWord; dX: LongInt; dY: LongInt; dZ: LongInt; P: LongWord; T: Double); stdcall; external RTC5DLL;
procedure n_timed_para_jump_abs_3d(CardNo: LongWord; X: LongInt; Y: LongInt; Z: LongInt; P: LongWord; T: Double); stdcall; external RTC5DLL;
procedure n_timed_para_jump_rel_3d(CardNo: LongWord; dX: LongInt; dY: LongInt; dZ: LongInt; P: LongWord; T: Double); stdcall; external RTC5DLL;
procedure n_timed_para_mark_abs(CardNo: LongWord; X: LongInt; Y: LongInt; P: LongWord; T: Double); stdcall; external RTC5DLL;
procedure n_timed_para_mark_rel(CardNo: LongWord; dX: LongInt; dY: LongInt; P: LongWord; T: Double); stdcall; external RTC5DLL;
procedure n_timed_para_jump_abs(CardNo: LongWord; X: LongInt; Y: LongInt; P: LongWord; T: Double); stdcall; external RTC5DLL;
procedure n_timed_para_jump_rel(CardNo: LongWord; dX: LongInt; dY: LongInt; P: LongWord; T: Double); stdcall; external RTC5DLL;
procedure timed_para_mark_abs_3d(X: LongInt; Y: LongInt; Z: LongInt; P: LongWord; T: Double); stdcall; external RTC5DLL;
procedure timed_para_mark_rel_3d(dX: LongInt; dY: LongInt; dZ: LongInt; P: LongWord; T: Double); stdcall; external RTC5DLL;
procedure timed_para_jump_abs_3d(X: LongInt; Y: LongInt; Z: LongInt; P: LongWord; T: Double); stdcall; external RTC5DLL;
procedure timed_para_jump_rel_3d(dX: LongInt; dY: LongInt; dZ: LongInt; P: LongWord; T: Double); stdcall; external RTC5DLL;
procedure timed_para_mark_abs(X: LongInt; Y: LongInt; P: LongWord; T: Double); stdcall; external RTC5DLL;
procedure timed_para_mark_rel(dX: LongInt; dY: LongInt; P: LongWord; T: Double); stdcall; external RTC5DLL;
procedure timed_para_jump_abs(X: LongInt; Y: LongInt; P: LongWord; T: Double); stdcall; external RTC5DLL;
procedure timed_para_jump_rel(dX: LongInt; dY: LongInt; P: LongWord; T: Double); stdcall; external RTC5DLL;
procedure n_set_defocus_list(CardNo: LongWord; Shift: LongInt); stdcall; external RTC5DLL;
procedure set_defocus_list(Shift: LongInt); stdcall; external RTC5DLL;
procedure n_timed_arc_abs(CardNo: LongWord; X: LongInt; Y: LongInt; Angle: Double; T: Double); stdcall; external RTC5DLL;
procedure n_timed_arc_rel(CardNo: LongWord; dX: LongInt; dY: LongInt; Angle: Double; T: Double); stdcall; external RTC5DLL;
procedure timed_arc_abs(X: LongInt; Y: LongInt; Angle: Double; T: Double); stdcall; external RTC5DLL;
procedure timed_arc_rel(dX: LongInt; dY: LongInt; Angle: Double; T: Double); stdcall; external RTC5DLL;
procedure n_arc_abs_3d(CardNo: LongWord; X: LongInt; Y: LongInt; Z: LongInt; Angle: Double); stdcall; external RTC5DLL;
procedure n_arc_rel_3d(CardNo: LongWord; dX: LongInt; dY: LongInt; dZ: LongInt; Angle: Double); stdcall; external RTC5DLL;
procedure n_arc_abs(CardNo: LongWord; X: LongInt; Y: LongInt; Angle: Double); stdcall; external RTC5DLL;
procedure n_arc_rel(CardNo: LongWord; dX: LongInt; dY: LongInt; Angle: Double); stdcall; external RTC5DLL;
procedure n_set_ellipse(CardNo: LongWord; A: LongWord; B: LongWord; Phi0: Double; Phi: Double); stdcall; external RTC5DLL;
procedure n_mark_ellipse_abs(CardNo: LongWord; X: LongInt; Y: LongInt; Alpha: Double); stdcall; external RTC5DLL;
procedure n_mark_ellipse_rel(CardNo: LongWord; dX: LongInt; dY: LongInt; Alpha: Double); stdcall; external RTC5DLL;
procedure arc_abs_3d(X: LongInt; Y: LongInt; Z: LongInt; Angle: Double); stdcall; external RTC5DLL;
procedure arc_rel_3d(dX: LongInt; dY: LongInt; dZ: LongInt; Angle: Double); stdcall; external RTC5DLL;
procedure arc_abs(X: LongInt; Y: LongInt; Angle: Double); stdcall; external RTC5DLL;
procedure arc_rel(dX: LongInt; dY: LongInt; Angle: Double); stdcall; external RTC5DLL;
procedure set_ellipse(A: LongWord; B: LongWord; Phi0: Double; Phi: Double); stdcall; external RTC5DLL;
procedure mark_ellipse_abs(X: LongInt; Y: LongInt; Alpha: Double); stdcall; external RTC5DLL;
procedure mark_ellipse_rel(dX: LongInt; dY: LongInt; Alpha: Double); stdcall; external RTC5DLL;
procedure n_set_offset_xyz_list(CardNo: LongWord; HeadNo: LongWord; XOffset: LongInt; YOffset: LongInt; ZOffset: LongInt; at_once: LongWord); stdcall; external RTC5DLL;
procedure n_set_offset_list(CardNo: LongWord; HeadNo: LongWord; XOffset: LongInt; YOffset: LongInt; at_once: LongWord); stdcall; external RTC5DLL;
procedure n_set_matrix_list(CardNo: LongWord; HeadNo: LongWord; Ind1: LongWord; Ind2: LongWord; Mij: Double; at_once: LongWord); stdcall; external RTC5DLL;
procedure n_set_angle_list(CardNo: LongWord; HeadNo: LongWord; Angle: Double; at_once: LongWord); stdcall; external RTC5DLL;
procedure n_set_scale_list(CardNo: LongWord; HeadNo: LongWord; Scale: Double; at_once: LongWord); stdcall; external RTC5DLL;
procedure n_apply_mcbsp_list(CardNo: LongWord; HeadNo: LongWord; at_once: LongWord); stdcall; external RTC5DLL;
procedure set_offset_xyz_list(HeadNo: LongWord; XOffset: LongInt; YOffset: LongInt; ZOffset: LongInt; at_once: LongWord); stdcall; external RTC5DLL;
procedure set_offset_list(HeadNo: LongWord; XOffset: LongInt; YOffset: LongInt; at_once: LongWord); stdcall; external RTC5DLL;
procedure set_matrix_list(HeadNo: LongWord; Ind1: LongWord; Ind2: LongWord; Mij: Double; at_once: LongWord); stdcall; external RTC5DLL;
procedure set_angle_list(HeadNo: LongWord; Angle: Double; at_once: LongWord); stdcall; external RTC5DLL;
procedure set_scale_list(HeadNo: LongWord; Scale: Double; at_once: LongWord); stdcall; external RTC5DLL;
procedure apply_mcbsp_list(HeadNo: LongWord; at_once: LongWord); stdcall; external RTC5DLL;
procedure n_set_mark_speed(CardNo: LongWord; Speed: Double); stdcall; external RTC5DLL;
procedure n_set_jump_speed(CardNo: LongWord; Speed: Double); stdcall; external RTC5DLL;
procedure n_set_sky_writing_para_list(CardNo: LongWord; Timelag: Double; LaserOnShift: LongInt; Nprev: LongWord; Npost: LongWord); stdcall; external RTC5DLL;
procedure n_set_sky_writing_list(CardNo: LongWord; Timelag: Double; LaserOnShift: LongInt); stdcall; external RTC5DLL;
procedure n_set_scanner_delays(CardNo: LongWord; Jump: LongWord; Mark: LongWord; Polygon: LongWord); stdcall; external RTC5DLL;
procedure n_set_jump_tuning_list(CardNo: LongWord; Flag: LongInt); stdcall; external RTC5DLL;
procedure set_mark_speed(Speed: Double); stdcall; external RTC5DLL;
procedure set_jump_speed(Speed: Double); stdcall; external RTC5DLL;
procedure set_sky_writing_para_list(Timelag: Double; LaserOnShift: LongInt; Nprev: LongWord; Npost: LongWord); stdcall; external RTC5DLL;
procedure set_sky_writing_list(Timelag: Double; LaserOnShift: LongInt); stdcall; external RTC5DLL;
procedure set_scanner_delays(Jump: LongWord; Mark: LongWord; Polygon: LongWord); stdcall; external RTC5DLL;
procedure set_jump_tuning_list(Flag: LongInt); stdcall; external RTC5DLL;

implementation

end.
